version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install && npm rebuild node-sass

      # Builds, tests and checks
      - run:
          name: Build production application
          command: npm run build

      - run:
          name: Start local server
          command: npm run server:prod
          background: true

      - run:
          name: Run lighthouse tests
          command: npm run check:perf

      - run:
          name: Generate LCOV report
          command: npm run test -- --single-run --code-coverage

      # Send stats to MoM
      - run:
          name: Send stats to MoM
          command: npm run mom

      # save cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_artifacts:
          path: ./stats
          destination: stats

      - store_artifacts:
          path: ./coverage
          destination: stats
